# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "c58ed1a2-e57b-45cd-9eb7-f37ee1449edf"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build your iOS app
  gym(
    # scheme: "YourScheme"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "aacf7f91fd33f2ca187be1bacb93035f068ec4ae",
    build_secret: "0b67a11b6a63362d2698b06ed0183007a6effa03c78c6ea4675cd2f75f28a208"
  )
end
